routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\TransactionController;
use App\Models\Transaction;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/install', function(){
    Artisan::call('migrate');
    Artisan::call('db:seed');
    return "OK";
});
// Route::redirect('/', '/dashboard', 301);

Route::prefix('/')->middleware('auth')->group(function(){

    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('/product', ProductController::class);
    Route::resource('/category', CategoryController::class);
    Route::resource('/customer', CustomerController::class);

    Route::get('/transaction/create', [TransactionController::class, 'create'])
    ->name('transaction.create');
    Route::get('/transaction', [TransactionController::class, 'index'])
    ->name('transaction.index');
    Route::get('/transaction/{id}/show', [TransactionController::class, 'show'])
    ->name('transaction.show');

    Route::post('/transaction/save-troli', [TransactionController::class, 'saveTroli'])
    ->name('transaction.save-troli');
    Route::post('/transaction/save-transaksi', [TransactionController::class, 'saveTransaksi'])
    ->name('transaction.save-transaksi');
    Route::delete('/transaction/{id}', [TransactionController::class, 'destroy'])
    ->name('transaction.destroy');

});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
    protected $fillable = ['name', 'price', 'stock', 'category_id'];

    function troli(){
        return $this->hasMany(Troli::class);
    }

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Http\Request;
use RealRashid\SweetAlert\Facades\Alert;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // list product
        $data = Product::all();
        return view('product.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('product.create', ['categories' => Category::all()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        // dd($request);
        $this->validate($request, [
            'name' => 'required|min:3',
            'stock' => 'required|integer',
            'price' => 'required|integer',
            'category_id' => 'required|integer'
        ],[
            'name.required' => 'Nama produk harus diisi',
            'name.min' => 'Nama produk minimal 3 karakter',
            'price.required' => 'Harga harus diisi',
            'stock.required' => 'Stock produk harus diisi',
            'category_id.required' => 'category belum dipilih',
            ]);

        Product::create([
            'name' => $request->name,
            'price' => $request->price,
            'stock' => $request->stock,
            'category_id' => $request->category_id
        ]);

        Alert::success('Berhasil', 'produk berhasil disimpan');
        return redirect()->route('product.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('product.edit', ['data' => Product::find($id), 'categories' => Category::all()]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required|min:3',
            'stock' => 'required|integer',
            'price' => 'required|integer',
            'category_id' => 'required|integer'
        ],[
            'name.required' => 'Nama produk harus diisi',
            'name.min' => 'Nama produk minimal 3 karakter',
            'price.required' => 'Harga harus diisi',
            'stock.required' => 'Stock produk harus diisi',
            'category_id.required' => 'category belum dipilih',
            ]);

        Product::where('id', $id)
            ->update([
                'name' => $request->name,
                'price' => $request->price,
                'stock' => $request->stock,
                'category_id' => $request->category_id
        ]);

        Alert::success('Berhasil', 'produk berhasil diperbarui');
        return redirect()->route('product.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Product::destroy($id);
        Alert::success('Berhasil', 'produk berhasil dihapus');
        return redirect()->route('product.index');
    }
}

resources/views/product/create.blade.php
@extends('layout.app')

@section('content')
<div class="row">
    <div class="col-xl-8 col-lg-7">
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div
                class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Tambah Produk</h6>

            </div>
            <!-- Card Body -->
            <div class="card-body">
                <form method="POST" action="{{ route('product.store') }}">
                    @csrf
                    <div class="form-group">
                        <label for="">Nama produk</label>
                        <input value="{{ old('name') }}" name="name" type="text" class="form-control @error('name')
                            is-invalid
                        @enderror">
                        @error('name')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="">Harga</label>
                        <input value="{{ old('price') }}" name="price" type="number" class="form-control @error('price')
                            is-invalid
                        @enderror">
                        @error('price')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="">Stok</label>
                        <input value="{{ old('stock') }}" name="stock" type="number" class="form-control @error('stock')
                            is-invalid
                        @enderror">
                        @error('stock')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>

                   <div class="form-group">
                       <label for="">Kategori</label>
                    <select name="category_id" class="form-select form-control @error('category_id')
                    is-invalid
                @enderror">
                @error('category_id')
                <div class="invalid-feedback">
                    {{ $message }}
                </div>
                @enderror">
                        <option value="">--- pilih kategori ---</option>
                        @forelse ($categories as $item)
                            <option value="{{ $item->id }}">{{ $item->name }}</option>
                        @empty
                            <option value="">-- tambah kategori terlebih dahulu!! --</option>
                        @endforelse
                    </select>
                    @error('category_id')
                    <div class="invalid-feedback d-block">
                        {{ $message }}
                    </div>
                    @enderror
                   </div>



                    <button class="d-block btn btn-primary" type="submit">Save</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/product/edit.blade.php
@extends('layout.app')

@section('content')
<div class="row">
    <div class="col-xl-8 col-lg-7">
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div
                class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Ubah produk</h6>

            </div>
            <!-- Card Body -->
            <div class="card-body">
                <form method="POST" action="{{ route('product.update',  $data->id ) }}">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label for="">Nama produk</label>
                        <input value="{{ old('name') ? old('name') : $data['name'] }}" name="name" type="text" class="form-control @error('name')
                            is-invalid
                        @enderror">
                        @error('name')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="">Harga</label>
                        <input value="{{ old('price') ? old('price') : $data['price'] }}" name="price" type="number" class="form-control @error('price')
                            is-invalid
                        @enderror">
                        @error('price')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="">Stok</label>
                        <input value="{{ old('stock') ? old('stock') : $data['stock'] }}" name="stock" type="number" class="form-control @error('stock')
                            is-invalid
                        @enderror">
                        @error('stock')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>

                   <div class="form-group">
                       <label for="">Kategori</label>
                    <select name="category_id" class="form-select form-control @error('category_id')
                    is-invalid
                @enderror">
                @error('category_id')
                <div class="invalid-feedback">
                    {{ $message }}
                </div>
                @enderror">
                        <option value="">--- Pilih kategori ---</option>
                        @forelse ($categories as $item)
                            <option {{ $item->id == $data['category_id'] ? 'selected' : '' }} value="{{ $item->id }}">{{ $item->name }}</option>
                        @empty
                            <option value="">-- silahlan tambah kategori terlebih dahulu --</option>
                        @endforelse
                    </select>
                    @error('category_id')
                    <div class="invalid-feedback d-block">
                        {{ $message }}
                    </div>
                    @enderror
                   </div>



                    <button class="btn btn-primary" type="submit">Perbarui produk</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/product/index.blade.php
@extends('layout.app')

@section('content')
    <!-- Content Row -->

    <div class="row">

        <div class="col-xl-8 col-lg-7">

            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div
                    class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Daftar produk</h6>
                    <a href="{{ route('product.create') }}" class="btn btn-primary btn-sm">Tambah</a>

                </div>
                <!-- Card Body -->
                <div class="card-body">
                   <table id="dataTable" class="table table-bordered" width="100%" tablespacing="0">
                        <thead>
                            <tr>
                                <th>No.</th>
                                <th>Nama produk</th>
                                <th>Kategori</th>
                                <th>Stok</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>

                        <tbody>
                           @forelse ($data as $item)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $item->name }}</td>
                                <td>{{ $item->category_id }}</td>
                                <td>{{ $item->stock }}</td>
                                <td>
                                    <a href="{{ route('product.edit', $item->id) }}" class="btn btn-warning">Edit</a>
                                    <form style="display: inline" action="{{ route('product.destroy', $item->id) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger">Delete</button>
                                    </form>
                                </td>
                            </tr>
                           @empty
                            @php
                                Alert::warning('Data produk kosong', 'silahkan tambah produk terlebih dahulu');
                            @endphp
                               <tr>
                                   <td style="text-align: center" colspan="5"><b>Data Kosong</b></td>
                               </tr>
                           @endforelse
                        </tbody>
                   </table>
                </div>
            </div>
        </div>
    </div>
@endsection