routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\TransactionController;
use App\Models\Transaction;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/install', function(){
    Artisan::call('migrate');
    Artisan::call('db:seed');
    return "OK";
});
// Route::redirect('/', '/dashboard', 301);

Route::prefix('/')->middleware('auth')->group(function(){

    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('/product', ProductController::class);
    Route::resource('/category', CategoryController::class);
    Route::resource('/customer', CustomerController::class);

    Route::get('/transaction/create', [TransactionController::class, 'create'])
    ->name('transaction.create');
    Route::get('/transaction', [TransactionController::class, 'index'])
    ->name('transaction.index');
    Route::get('/transaction/{id}/show', [TransactionController::class, 'show'])
    ->name('transaction.show');

    Route::post('/transaction/save-troli', [TransactionController::class, 'saveTroli'])
    ->name('transaction.save-troli');
    Route::post('/transaction/save-transaksi', [TransactionController::class, 'saveTransaksi'])
    ->name('transaction.save-transaksi');
    Route::delete('/transaction/{id}', [TransactionController::class, 'destroy'])
    ->name('transaction.destroy');

});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;
    protected $fillable = ['name'];
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;
use RealRashid\SweetAlert\Facades\Alert;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('category.index', ['data' => Category::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // form
        return view('category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request, [
            'name' => 'required|min:3',
        ],
        [
            'name.required' => 'Nama kategory harus diisi',
            'name.min' => 'Nama kategory minimal 3 karakter'
        ]);

        Category::create([
            'name' => $request->name
        ]);

        Alert::success('Berhasil','Kategori berhasil dibuat');
        return redirect(route('category.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('category.edit', ['data' => Category::find($id)]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $this->validate($request, [
            'name' => 'required|min:3',
        ],
        [
            'name.required' => 'Nama kategory harus diisi',
            'name.min' => 'Nama kategory minimal 3 karakter'
        ]);

        Category::where('id', $id)
            ->update([
                'name' => $request->name
            ]);

            Alert::success('Berhasil','Kategori berhasil diperbarui');
            return redirect(route('category.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        Category::destroy($id);
        Alert::success('Berhasil','Kategori berhasil dihapus');
        return redirect(route('category.index'));
    }
}

resources/views/category/create.blade.php
@extends('layout.app')

@section('content')
<div class="row">
    <div class="col-xl-8 col-lg-7">
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div
                class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Tambah kategori</h6>

            </div>
            <!-- Card Body -->
            <div class="card-body">
                <form method="POST" action="{{ route('category.store') }}">
                    @csrf
                    <div class="form-group">
                        <label for="">Nama kategori</label>
                        <input value="{{ old('name') }}" name="name" type="text" class="form-control @error('name')
                            is-invalid
                        @enderror">
                        @error('name')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>

                    <button class="btn btn-primary" type="submit">Simpan</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/category/edit.blade.php
@extends('layout.app')

@section('content')
<div class="row">
    <div class="col-xl-8 col-lg-7">
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div
                class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Ubah kategori</h6>

            </div>
            <!-- Card Body -->
            <div class="card-body">
                <form method="POST" action="{{ route('category.update',  $data->id ) }}">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label for="">Nama kategori</label>
                        <input value="{{ old('name') ? old('name') : $data['name'] }}" name="name" type="text" class="form-control @error('name')
                            is-invalid
                        @enderror">
                        @error('name')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>



                    <button class="btn btn-primary" type="submit">Perbarui</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/category/index.blade.php
@extends('layout.app')

@section('content')
    <!-- Content Row -->

    <div class="row">
        <div class="col-xl-8 col-lg-7">


            @if (Session::has('message'))
            <div class="alert alert-success">
                {{ Session::get('message') }}
            </div>
            @endif

            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div
                    class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Daftar kategori</h6>
                    <a href="{{ route('category.create') }}" class="btn btn-sm btn-primary">Tambah kategori</a>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                   <table class="table table-bordered" width="100%" tablespacing="0">
                        <thead>
                            <tr>
                                <th>No.</th>
                                <th>Nama</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>


                        <tbody>
                           @forelse ($data as $item)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $item->name }}</td>
                                <td>
                                    <a href="{{ route('category.edit', $item->id) }}" class="btn btn-sm btn-warning">Ubah</a>
                                    <form style="display: inline" action="{{ route('category.destroy', $item->id) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-sm btn-danger">Hapus</button>
                                    </form>
                                </td>
                            </tr>
                           @empty
                               <tr>
                                   <td style="text-align: center" colspan="5"><b>Data Kosong</b></td>
                               </tr>
                           @endforelse
                        </tbody>
                   </table>
                </div>
            </div>
        </div>
    </div>
@endsection