routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\TransactionController;
use App\Models\Transaction;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/install', function(){
    Artisan::call('migrate');
    Artisan::call('db:seed');
    return "OK";
});
// Route::redirect('/', '/dashboard', 301);

Route::prefix('/')->middleware('auth')->group(function(){

    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('/product', ProductController::class);
    Route::resource('/category', CategoryController::class);
    Route::resource('/customer', CustomerController::class);

    Route::get('/transaction/create', [TransactionController::class, 'create'])
    ->name('transaction.create');
    Route::get('/transaction', [TransactionController::class, 'index'])
    ->name('transaction.index');
    Route::get('/transaction/{id}/show', [TransactionController::class, 'show'])
    ->name('transaction.show');

    Route::post('/transaction/save-troli', [TransactionController::class, 'saveTroli'])
    ->name('transaction.save-troli');
    Route::post('/transaction/save-transaksi', [TransactionController::class, 'saveTransaksi'])
    ->name('transaction.save-transaksi');
    Route::delete('/transaction/{id}', [TransactionController::class, 'destroy'])
    ->name('transaction.destroy');

});

app/Models/Customer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    use HasFactory;
    protected $fillable = ['name', 'phone', 'email'];
}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use App\Models\Customer;
use App\Models\Product;
use Illuminate\Http\Request;

class CustomerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('customer.index', ['data' => Customer::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('customer.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|min:3',
            'phone' => 'required',
            'email' => 'required',
        ],[
            'name.required' => 'Nama produk harus diisi',
            'name.min' => 'Nama produk minimal 3 karakter',
            'phone.required' => 'no. wa harus diisi',
            'email.required' => 'email harus diisi',

            ]);


        $id = Customer::create([
            'name' => $request->name,
            'phone' => $request->phone,
            'email' => $request->email
        ]);

        if(!empty($request->redir)){
            return redirect($request->redir.'?customer_id='.$id->id);
        }
        return redirect()->back()->with('message','customer has been saved');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('customer.edit', ['data' => Customer::find($id)]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required|min:3',
            'phone' => 'required',
            'email' => 'required',
        ],[
            'name.required' => 'Nama produk harus diisi',
            'name.min' => 'Nama produk minimal 3 karakter',
            'phone.required' => 'no. wa harus diisi',
            'email.required' => 'email harus diisi',

            ]);


        Customer::where('id', $id)
            ->update([
                'name' => $request->name,
                'phone' => $request->phone,
                'email' => $request->email
        ]);

        return redirect()->back()->with('message','customer has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Customer::destroy($id);
        return redirect()->back()->with('message','customer has been deleted');

    }
}

resources/views/customer/create.blade.php
@extends('layout.app')

@section('content')
<div class="row">
    <div class="col-xl-8 col-lg-7">
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div
                class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Tambah konsumen</h6>

            </div>
            <!-- Card Body -->
            <div class="card-body">

                <form method="POST" action="{{ route('customer.store') }}">
                    @csrf
                    <input type="hidden" name="redir" value="{{ Request::get('redir') }}">
                <div class="form-group">
                    <label for="">Nama konsumen</label>
                    <input value="{{ old('name') ? old('name') : ''}}" name="name" type="text" class="form-control @error('name')
                        is-invalid
                    @enderror">
                    @error('name')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="">No. wa</label>
                    <input value="{{ old('phone') ? old('phone') : '' }}" name="phone" type="number" class="form-control @error('phone')
                        is-invalid
                    @enderror">
                    @error('phone')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="">Email</label>
                    <input value="{{ old('email') ? old('email') : '' }}" name="email" type="email" class="form-control @error('email')
                        is-invalid
                    @enderror">
                    @error('email')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>




                    <button class="d-block btn btn-primary" type="submit">Simpan</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/customer/edit.blade.php
@extends('layout.app')

@section('content')
<div class="row">
    <div class="col-xl-8 col-lg-7">
        @if (Session::has('message'))
        <div class="alert alert-success">
            {{ Session::get('message') }}
        </div>
        @endif
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div
                class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Ubah data konsumen {{ $data->name }}</h6>

            </div>
            <!-- Card Body -->
            <div class="card-body">
                <form method="POST" action="{{ route('customer.update',  $data->id ) }}">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label for="">Name</label>
                        <input value="{{ old('name') ? old('name') : $data['name'] }}" name="name" type="text" class="form-control @error('name')
                            is-invalid
                        @enderror">
                        @error('name')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="">No. wa</label>
                        <input value="{{ old('phone') ? old('phone') : $data['phone'] }}" name="phone" type="number" class="form-control @error('phone')
                            is-invalid
                        @enderror">
                        @error('phone')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="">Email</label>
                        <input value="{{ old('email') ? old('email') : $data['email'] }}" name="email" type="email" class="form-control @error('email')
                            is-invalid
                        @enderror">
                        @error('email')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>



                    <button class="btn btn-primary" type="submit">Perbarui</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/customer/index.blade.php
@extends('layout.app')

@section('content')
    <!-- Content Row -->

    <div class="row">

        <!-- Area Chart -->
        <div class="col-xl-8 col-lg-7">
            @if (Session::has('message'))
            <div class="alert alert-success">
                {{ Session::get('message') }}
            </div>
            @endif

            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div
                    class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Daftar konsumen</h6>
                    <a href="{{ route('customer.create') }}" class="btn btn-primary btn-sm">Tambah konsumen</a>

                </div>
                <!-- Card Body -->
                <div class="card-body">
                   <table class="table table-bordered" width="100%" tablespacing="0">
                        <thead>
                            <tr>
                                <th>No.</th>
                                <th>Nama konsumen</th>
                                <th>No. Wa</th>
                                <th>Email</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>

                        <tbody>
                           @forelse ($data as $item)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $item->name }}</td>
                                <td>{{ $item->phone }}</td>
                                <td>{{ $item->email }}</td>
                                <td>
                                    <a href="{{ route('customer.edit', $item->id) }}" class="btn btn-warning btn-sm">Ubah</a>
                                    <form style="display: inline" action="{{ route('customer.destroy', $item->id) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger btn-sm">Hapus</button>
                                    </form>
                                </td>
                            </tr>
                           @empty
                               <tr>
                                   <td style="text-align: center" colspan="5"><b>Data Kosong</b></td>
                               </tr>
                           @endforelse
                        </tbody>
                   </table>
                </div>
            </div>
        </div>
    </div>
@endsection